### ISSUE TITLE
toml input does not support multiple tasks on the same day

### ISSUE THREAD

**Issue by Luro02** [Luro02/time-sheet#10]
This is obviously not possible
```toml
[days.02]
action = "did one thing"
start = "08:00"
end = "13:00"

[days.02]
action = "did another thing"
start = "15:00"
end = "18:00"
```
because toml keys can not be duplicate.
