### ISSUE TITLE
Add option to automatically add holiday time

### ISSUE THREAD

**Issue by Luro02** [Luro02/time-sheet#11]
Holiday hours are calculated by this formula:
```
(hours per month) * (20 holidays per year)
------------------------------------------  * (3.95 hours per day) = (X hours per year)
          (85 hours per month)
```
For contract changes, this number has to be recalculated.

### Contracts running less than a year
You could have a contract from 2022-10-01 to 2023-02-28 with 40 hours per month.

Then, by the formula `(40 * 20)/85 * 3.95 ≈ 37.176 hours per year` (number should be rounded up at .5). To be exact: 2230.6 mins per year = 2231 mins per year of holiday time.
The person will not be working for an entire year, so the value has to be divided by 12 and multiplied by the number of **full** months for which the contract is valid for.

In this case, a 5-month-long contract => 2231/12 * 5 = 929.6 mins = 930 mins. (Note: because of previous rounding, this value may be inaccurate).

# Implementation

## What to be careful about:
- [x] It is not required to know how long a contract is running in the month file (it is already assumed by default that a contract starts/ends with the first/last day of the month). Therefore, one only needs to adjust the formula to return the number of holidays in a month.
- [x] Rounding may result in inaccurate numbers.
- [x] Only full months count, so for a contract starting at the 15th march, the month march would not be counted?

## `toml`
In the config, a new section will be added
```toml
[holiday]
implicit = true # by default false, if true the holiday hours are automatically added to the contract
week_day = "monday" # on which day the holiday hours should be added
day = "1" # alternatively specify the day explicitly
```

additionally, one will be able to specify them explicitly for entries:
```toml
[days.03]
action = "wrote python script"
start = "10:00"
end = "15:00"
holiday = "+01:00" # prefix with +/- to explicitly add the time before the start (-) or after the end (+). Without the prefix it will be added to the end if possible, otherwise to the front or an error will occur.
```
