### ISSUE TITLE
Add support for specifying absence

### ISSUE THREAD

**Issue by Luro02** [Luro02/time-sheet#13]
With #4 and #7 one should have the option to specify timespans/days in which one could not have done work or regular events have not taken place, because of for example illness.

```toml
[absence.02]
start = "10:00"
end = "23:59"
```

```toml
[absence."02-10"]
start = "10:00" # start time on the first day
end = "23:59"   # end time on the last day
```

```toml
[absence.monday]
start = "10:00"
end = "12:00"
```

Might as well be useful to influence the dynamic distribution algorithm.
