### ISSUE TITLE
Ensure transfer time is not ignored

### ISSUE THREAD

**Issue by Luro02** [Luro02/time-sheet#14]
Right now it is unclear whether or not the scheduler takes the transfer time into account. For example a 40hour job and this transfer header in the month file:
```toml
[transfer]
next = "04:00"
prev = "01:00"
```
the total worked time in that month should be 43 hours with the transfer time.

### Todo
- [x] ensure that it works
- [x] write some tests for this
