### ISSUE TITLE
Department should be specified by the month file

### ISSUE THREAD

**Issue by Luro02** [Luro02/time-sheet#22]
```toml
[general]
month = 11
year = 2022
department = "MENSA"
```
This should be added, so the program can automatically choose the correct contract from the global file and complain if the contract has expired or is missing.
