### ISSUE TITLE
Add support for repeating events

### ISSUE THREAD

**Issue by Luro02** [Luro02/time-sheet#4]
Input from #3 could look like this:

```toml
[monday]
name = "Regular meeting"
repeats = "weekly"
start_date = 2022-01-01
start = "09:00"
end = "11:00"
```

(this could be used to easily add support for like weekly or biweekly meetings)

What may be problematic
- [ ] finding on which dates in the month the event will apply
- [ ] skipping holidays
- [ ] add an option to skip specific dates, because for example the organizer was ill;
```toml
[regular meeting.2022-01-04]
skip = true
reason = "nobody available"
```
