### ISSUE TITLE
Add support for flexibly filling up time slots

### ISSUE THREAD

**Issue by Luro02** [Luro02/time-sheet#7]
For example, one could have done the following in a month:
- wrote a python script
- helped out with grading assignments
- prepared for next presentation

On the time-sheet must be 40h, but you can not always remember when and for how long you worked.

Therefore, a new config option will be added to specify variable entries:
```toml
[days.10]
action = "wrote python script"
start = "10:00"
end = "15:00"
flex = "01:00" # <- this entry can vary by +- 1 hour
# additonally if the entry should only vary in one direction,
# then one can do this:
# flex = "+01:00" # <- will only add to the end
# flex = "-01:00" # <- will only subtract
```
This can make it easier to write down tasks without having to worry about exactly matching 40h in total.
Pauses are automatically added. (Here special care needs to be taken, so that no invalid entries are created)

There are some tasks where it does not really matter when they have been executed,
so one can use the `dynamic` entries:
```toml
# [dynamic.<action>]
[dynamic."wrote a python script"]
# how much time has been occupied by this task in total.
# In this example 12 hours and 43 minutes.
duration = "12:43"
```

If there is no time estimate, then simply specify the ratio between the different dynamic entries:
```toml
[dynamic."helped out with grading assignments"]
flex = 1

[dynamic."prepared for next presentation"]
flex = 2
```
In the above, the two dynamic entries take up 100% of the remaining time. For example, if there are 30h of remaining time, then 1/3 (10h) would be occupied by the `"helped out with grading assignments"` task and 2/3 (20h) by the `"prepared for next presentation"`.

The amount of time it takes can be calculated like this:
```rust
/// Returns the time that the provided entry with `entry_flex` occupies.
// TODO: care must be taken that the remaining time of all entries is not exceeded, because of rounding!
fn calculate_time(entry_flex: usize, flex_entries: &[usize], remaining: WorkingDuration) -> WorkingDuration {
  let total = flex_entries.iter().copied().sum() as f64;
  let ratio: f64 = (entry_flex as f64) / total;
  
  remaining * ratio
}
```
